name: ci
on:
  push:
    branches:
      - main
      - master

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install mkdocs-material "mkdocs-material[imaging]"
      - run: mkdocs gh-deploy --force
